name: razorpay_web
description: Razorpay Web Payment Gateway for Flutter
version: 1.1.0
homepage: "https://github.com/gauravmehta13/razorpay_web"

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:

  